version: '3' 
services:
    tensorflow-workspace:
      image: ${USER_NAME}/tensorflow_workspace
      container_name: tensorflow_workspace 
      privileged: true
      environment:
          - DISPLAY=${IP}:0.0
      network_mode: host
      build:
          context: ../tensorflow_ws
          args: 
            - USER_NAME=${USER_NAME}
      user: ${USER_NAME}
      volumes:
          - ../tensorflow_ws/workspace:/home/${USER_NAME}/workspace
          - ../datas:/home/${USER_NAME}/datas
      deploy:
          resources:
              reservations:
                  devices:
                  - driver: nvidia
                    count: all
                    capabilities: [gpu]
      restart: always
      command: sleep infinity
